version: '3'
services:
  ask-app:
    container_name: document-container
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    command: python manage.py runserver 0.0.0.0:8000
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '1'

    volumes:
      - 'psql:/var/lib/postgresql/data'
volumes:
  psql: