# Generated by Django 4.2.4 on 2023-08-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='number_pages',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='width',
        ),
    ]
