# Generated by Django 4.2.4 on 2023-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_height_image_num_pages_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='num_pages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(),
        ),
    ]
