# Generated by Django 4.2.4 on 2023-08-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_height_alter_image_num_pages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='num_pages',
            new_name='channels',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='channels',
            new_name='num_pages',
        ),
    ]
